### ISSUE TITLE
outdated login API

### ISSUE THREAD

**Issue by klepsydra** [rememberlenny/robinhood-ruby#5]
Seems like the login/credentials part needs updating.
 
```
irb(main):014:0* @robinhood = Robinhood::REST::Client.new(username, password)
JSON::ParserError: 765: unexpected token at '<h1>Not Found</h1><p>The requested URL /api-token-auth/ was not found on this server.</p>'
        from /var/lib/gems/2.3.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
        from /var/lib/gems/2.3.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
        from /var/lib/gems/2.3.0/gems/robinhood-ruby-0.4.4/lib/robinhood-ruby/rest/client.rb:88:in `login'
        from /var/lib/gems/2.3.0/gems/robinhood-ruby-0.4.4/lib/robinhood-ruby/rest/client.rb:19:in `initialize'
        from (irb):14:in `new'
        from (irb):14
        from /usr/bin/irb:11:in `<main>'
irb(main):015:0> 

```

**Comment by mmahalwy** [comment]
@klepsydra same here. Any luck getting around this?
